on: [push, pull_request]

name: Continuous integration

jobs:
  test:
    name: Test Suite
    strategy:
      matrix:
        rust:
          - stable
          - 1.63.0
          - nightly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust }}
      - run: cargo test